# -*- coding: utf-8 -*-
"""0-introduction-to-python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mj2f59kW6pkU45nbuprYkAYytrAaeBrF
"""

import numpy as np
x = np.array([1,2,3])
x1 = np.array([4,3,2])

a = np.zeros((2, 2))
b = np.zeros((2, 2))

c = np.random.randint(10, size=(5))
d = np.random.randint(10, size=(5))

f1 = np.random.random((2, 2))

print(x-x1)
print(a-b)
print(np.dot(x, x1))
print(np.argmax(x1))

for n in x:
  print(n, end='-')


print(a.dtype)
print(np.argmax(f1))
print(np.sum(a))

#Relational Operation

