# -*- coding: utf-8 -*-
"""1-introduction-to-numpy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h85AGx6gPpRZu7eB2yCU2enyjMUbBP8E
"""

import numpy as np
a = np.asmatrix([[22,5,16,9],[13,20,19,0],[5,9,1,16],[27,13,15,19]])
b = np.asmatrix([[10,5,20,20], [5,21,22,27], [26,19,22,3], [27,8,18,7]])
c = np.array([24, 3, 17, 7, 11, 2, 21, 2, 24, 18, 3, 11, 14, 25, 2, 20])
d = np.array([3, 15, 24, 22, 19, 24, 4, 29, 6, 3, 20, 1, 11, 25, 26, 6])
#
print(a)
print(b)
print(c)
print(d)

#1 addition
print(a + b)

#2 substraction
print(a-b)

#3 multiplication
print(a * b)

#4 multiplication
print(np.dot(a, b))

#5
print(c+d)

#6
print(c-d)

#7
print(c*d)

#8
print(np.dot(c, d))

#9
print(a+10)

#10
print(b+10)

#11
print(c+15)

#12
print(d+15)

#13


print((2*a) + (2*b))

#14
print((a+b) * 3)

#15
print((a- b + a - b + b) * 4)

