# -*- coding: utf-8 -*-
"""2-introduction-to-pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WPCREmfDIftA2F7bFB87tzqG6bqkks6n
"""

import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/sassoftware/sas-viya-programming/master/data/cars.csv')
df.head()

df.columns

df.dtypes

df.info()

subdf = df[['Make', 'Model', 'Horsepower']]
subdf.head()

# model = df['Model']
model = df.Model
model.head()

#access rows only 3 to 6
df.iloc[3:7]

df.iloc[[4,5,10,12,15]]

df = df.set_index('Model')
df.head()

df.loc['MDX']

df.loc[['TSX 4dr', 'TL 4dr']]

df.iloc[1:5, 3:6] # rows 1 - 4 column 3 to 5

df['MSRP'] > 2000

#df.EngineSize(df.EngineSize==2.4)
df[df.EngineSize==2.4]

df.describe()

df.min()

df.max()

df.MSRP.describe()

df['MSRP'].describe()

grpdf = df.groupby('Origin')
grpdf.describe()

df.plot(kind='scatter', x='MSRP', y='Horsepower', figsize=(12,6))

df.corr()





