# -*- coding: utf-8 -*-
"""4-introduction-to-tensorflow.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VdDss47BxJGAw_M8D66LoFt-BOmoc8JI
"""

import tensorflow as tf

# place holder for input
x = tf.placeholder(dtype=tf.float32)

# define computational graph
y = tf.pow((2 * x), 2) + (2 * x) + 1

# initialize the variables
init_op = tf.global_variables_initializer()

# create session
sess = tf.Session()

# run session
sess.run(init_op)

# run computational graph with input 10 to x
value = sess.run(y, feed_dict={x: 10})

print(value)

# create random variable
weights = tf.Variable(tf.random_normal(shape=[10]))

sess.run(tf.global_variables_initializer())

sess.run(weights)



